language: swift
os: osx
osx_image: xcode12.2
before_install:
  - touch TestCredentials.xcconfig
  - brew install jq
jobs:
  include:
    - stage: Test
      name: iOS Unit Tests
      script:
      - xcodebuild -workspace okta-idx.xcworkspace -scheme "okta-idx-ios" -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" clean test
    - stage: Test
      name: iOS Automated Tests
      before_script:
      - ./scripts/setup-automation.sh
      script:
      - xcodebuild -workspace okta-idx.xcworkspace -scheme "OktaIdxExample" -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" clean test
      after_script:
      - ./scripts/teardown-automation.sh
    - stage: Package Management
      name: Swift Package Manager
      script:
      - swift test
    - stage: Package Management
      name: Cocoapods
      script:
      - pod lib lint
    # Disable Carthage validation until we can get it working
    #- stage: Package Management
    #  name: Carthage
    #  script:
    #  - carthage build --use-xcframeworks --no-skip-current
