language: objective-c
osx_image: xcode11.5
jobs:
  include:
    - stage: Unit tests iOS
      name: iOS
      script:
      - xcodebuild -workspace okta-idx.xcworkspace -scheme "okta-idx-ios" -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" clean test
    # Current CI doesn't support Swift 5.3.0, which is required by unit tests
    #- stage: Swift Package Manager validation
    #  name: MacOS
    #  script:
    #  - swift test
    - stage: UI tests iOS
      name: iOS
      script:
      - xcodebuild -workspace okta-idx.xcworkspace -scheme "OktaIdxExample" -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" clean test
    - stage: Cocoapods validation
      name: iOS
      script:
      - pod lib lint
    - stage: Carthage validation
      name: iOS
      script:
      - carthage build --no-skip-current
