// Copyright (c) 2023-Present, Okta, Inc. and/or its affiliates. All rights reserved.
// The Okta software accompanied by this notice is provided pursuant to the Apache License, Version 2.0 (the "License.")
//
// You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and limitations under the License.
//

import Foundation

/**
 This member contains the type of the public key credential the caller is referring to.
 
 - Note: [W3C Reccomendation](https://www.w3.org/TR/webauthn/#enum-attestation-convey)
 */
public enum AttestationConveyancePreference: String, Codable {
    /// This value indicates that the Relying Party wants to receive the attestation statement as generated by the authenticator.
    case direct
    /// This value indicates that the Relying Party wants to receive an attestation statement that may include uniquely identifying information.
    case enterprise
    /// This value indicates that the Relying Party prefers an attestation conveyance yielding verifiable attestation statements, but allows the client to decide how to obtain such attestation statements.
    case indirect
    /// This value indicates that the Relying Party is not interested in authenticator attestation.
    case none
}
