//
//  AttestationConveyancePreference.swift
//  Okta Verify
//
//  Created by Michael Biviano on 10/6/22.
//  Copyright © 2022 Okta. All rights reserved.
//

import Foundation

/**
 This member contains the type of the public key credential the caller is referring to.
 
 - Note: [W3C Reccomendation](https://www.w3.org/TR/webauthn/#enum-attestation-convey)
 */
enum AttestationConveyancePreference: String, Codable {
    /// This value indicates that the Relying Party wants to receive the attestation statement as generated by the authenticator.
    case direct
    /// This value indicates that the Relying Party wants to receive an attestation statement that may include uniquely identifying information.
    case enterprise
    /// This value indicates that the Relying Party prefers an attestation conveyance yielding verifiable attestation statements, but allows the client to decide how to obtain such attestation statements.
    case indirect
    /// This value indicates that the Relying Party is not interested in authenticator attestation.
    case none
}
