name: Canary Tests

on:
  pull_request:
    paths:
      - '.github/workflows/lint.yml'
      - '.swiftlint.yml'
      - 'Sources/**/*.swift'
  push:
    paths:
      - '.github/workflows/lint.yml'
      - '.swiftlint.yml'
      - 'Sources/**/*.swift'
    branches:
      - master

jobs:
  SwiftLint:
	name: Lint Sources
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint code using SwiftLint
        run: swiftlint lint --reporter github-actions-logging Sources
