name: Package Managers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  #PackageValidation:
  #  runs-on: macos-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Cocoapods
  #    run: pod lib lint
