name: OktaIdx

on:
  push:
    branches:
      - master
      - dev-*
  pull_request:
    branches: 
      - master
      - dev-*

jobs:
  UnitTest:
    name: Unit Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - macos-latest
    steps:
    - name: Get swift version
      run: swift --version
    - uses: actions/checkout@master
    - name: Build
      run: swift build --build-tests
    - name: Test
      run: swift test
