name: Swift Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Xcode:
    runs-on: macos-11
    strategy:
      matrix:
        xcode: [ "13.1", "12.4" ]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - name: Xcode iOS Unit Tests
      run: xcodebuild -workspace okta-idx.xcworkspace -scheme "okta-idx-ios" -destination "platform=iOS Simulator,OS=latest,name=iPhone 11" clean test
    - name: Swift Tests
      run: swift test -v
    - name: Cocoapods Lint
      run: pod lib lint
